### ISSUE TITLE
Theia TODO

### ISSUE THREAD

**Issue by LeNitrous** [LeNitrous/theia#1]
This issue tracks planned features for `theia`. These are not ordered by priority.
- [ ] Custom Video Player
- [ ] Downloads
- [ ] Offline Support
- [ ] Discord Rich Presence Support
- [ ] Anime List Support
